import { NextResponse } from "next/server";
import { getSessionUser, sameOrigin } from "@/app/auth";
import { getDatabase } from "@/db";
import { ensurePropertySchema } from "@/app/api/app/properties";

const escapeHtml=(value:unknown)=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));
const id=()=>crypto.randomUUID();
type PassVehicle={id:string;community_id:string;plate:string;brand_model:string|null;color:string|null;owner_name:string;vehicle_type:string;valid_until:string|null;inside:number;unit_no:string|null;block_name:string|null;parking_code:string|null};
async function passContext(token:string,userId:string){
  const db=getDatabase(),vehicle=await db.prepare("SELECT v.id,v.community_id,v.plate,v.brand_model,v.color,v.owner_name,v.vehicle_type,v.valid_until,v.inside,u.unit_no,b.name AS block_name,p.code AS parking_code FROM vehicles v LEFT JOIN property_units u ON u.id=v.unit_id LEFT JOIN property_blocks b ON b.id=u.block_id LEFT JOIN parking_spots p ON p.id=v.parking_spot_id WHERE v.qr_token=? AND v.active=1").bind(token).first<PassVehicle>();if(!vehicle)return null;const membership=await db.prepare("SELECT role,display_name FROM members WHERE community_id=? AND user_id=?").bind(vehicle.community_id,userId).first<{role:string;display_name:string}>();if(!membership||!["owner","manager","security"].includes(membership.role))return null;return {vehicle,membership};
}

export async function GET(request:Request){
  const user=await getSessionUser(),url=new URL(request.url),token=url.searchParams.get("token")||"";if(!user)return NextResponse.redirect(new URL(`/giris?returnTo=${encodeURIComponent(url.pathname+url.search)}`,url.origin));await ensurePropertySchema();const context=await passContext(token,user.userId);if(!context)return new Response("Araç geçiş kartı bulunamadı veya bu işlem için yetkiniz yok.",{status:404,headers:{"content-type":"text/plain; charset=utf-8"}});const v=context.vehicle,expired=v.valid_until&&new Date(String(v.valid_until)).getTime()<Date.now(),unit=v.block_name?`${v.block_name} · Daire ${v.unit_no}`:"Daire atanmamış";
  return new Response(`<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(v.plate)} araç geçişi</title><style>*{box-sizing:border-box}body{margin:0;background:#eef5fb;color:#082846;font:16px/1.5 Arial,sans-serif}.card{width:min(92vw,440px);margin:7vh auto;padding:24px;border:1px solid #cfe0ee;border-radius:24px;background:#fff;box-shadow:0 22px 60px #073b7320}.brand{color:#087ff5;font-weight:900}.plate{margin:22px 0 8px;font-size:34px;font-weight:900;letter-spacing:.06em}.tag{display:inline-block;padding:5px 9px;border-radius:999px;background:${expired?'#fee8e8':'#dcf8f2'};color:${expired?'#a32929':'#08776c'};font-size:12px;font-weight:800}.info{margin:20px 0;padding:15px;border-radius:14px;background:#f3f7fb}.info p{display:flex;justify-content:space-between;gap:15px;margin:8px 0}.info span{color:#60758a}form{display:grid;grid-template-columns:1fr 1fr;gap:10px}input{grid-column:1/-1;padding:12px;border:1px solid #c9d9e7;border-radius:10px}button{padding:14px;border:0;border-radius:12px;color:#fff;font-weight:800;cursor:pointer}.entry{background:#0b9f83}.exit{background:#d7555f}.inside{margin:12px 0;font-weight:800}a{display:block;margin-top:18px;color:#087ff5;text-align:center;text-decoration:none}</style></head><body><main class="card"><div class="brand">apartmanOS · Araç Geçişi</div><div class="plate">${escapeHtml(v.plate)}</div><span class="tag">${expired?'Süresi dolmuş misafir aracı':v.vehicle_type==='guest'?'Misafir araç':'Kayıtlı araç'}</span><div class="info"><p><span>Araç</span><b>${escapeHtml(v.brand_model||'Belirtilmedi')} · ${escapeHtml(v.color||'—')}</b></p><p><span>Sahibi</span><b>${escapeHtml(v.owner_name)}</b></p><p><span>Daire</span><b>${escapeHtml(unit)}</b></p><p><span>Otopark</span><b>${escapeHtml(v.parking_code||'Atanmadı')}</b></p></div><p class="inside">Güncel durum: ${Number(v.inside)?'İçeride':'Dışarıda'}</p>${expired?'<p>Bu aracın geçiş süresi dolmuş. Yönetim onayı olmadan giriş kaydı oluşturmayın.</p>':`<form method="post" action="/api/vehicle-pass"><input type="hidden" name="token" value="${escapeHtml(token)}"><input name="gateName" value="Ana giriş" aria-label="Kapı adı"><button class="entry" name="eventType" value="entry">Giriş kaydet</button><button class="exit" name="eventType" value="exit">Çıkış kaydet</button></form>`}<a href="/giris">Yönetim paneline dön</a></main></body></html>`,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}});
}

export async function POST(request:Request){
  if(!sameOrigin(request))return new Response("Geçersiz istek.",{status:403});const user=await getSessionUser();if(!user)return new Response("Oturum açmanız gerekiyor.",{status:401});await ensurePropertySchema();const form=await request.formData(),token=String(form.get("token")||""),context=await passContext(token,user.userId);if(!context)return new Response("Araç veya yetki bulunamadı.",{status:404});const eventType=String(form.get("eventType"))==="exit"?"exit":"entry",createdAt=new Date().toISOString(),db=getDatabase();await db.batch([db.prepare("INSERT INTO vehicle_events (id,community_id,vehicle_id,event_type,gate_name,occurred_at,recorded_by,recorded_by_name) VALUES (?,?,?,?,?,?,?,?)").bind(id(),context.vehicle.community_id,context.vehicle.id,eventType,String(form.get("gateName")||"Ana giriş").slice(0,80),createdAt,user.userId,user.displayName),db.prepare("UPDATE vehicles SET inside=? WHERE id=?").bind(eventType==="entry"?1:0,context.vehicle.id)]);return NextResponse.redirect(new URL(`/api/vehicle-pass?token=${encodeURIComponent(token)}`,request.url),303);
}
