"use client";

import { ComponentProps, FormEvent, useEffect, useState } from "react";
import { Bell, BookOpenCheck, CircleDollarSign, Gauge, LogOut, Megaphone, Menu, Plus, ReceiptText, Settings, ShieldCheck, Trash2, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuBadge, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger, useSidebar } from "@/components/ui/sidebar";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";

type User = { displayName: string; email: string };
type Community = { id:string; name:string; block_count:number; unit_count:number; monthly_due:number; period:string; invite_code:string };
type Member = { id:string; display_name:string; email:string; role:"owner"|"manager"|"resident"; unit:string|null; joined_at:string };
type Resident = { id:string; name:string; unit:string; phone:string|null; occupancy:string };
type Due = { id:string; resident_name:string; unit:string; amount:number; status:"pending"|"paid"|"late"; due_date:string; created_at:string };
type Expense = { id:string; title:string; category:string; amount:number; note:string|null; expense_date:string; created_at:string };
type Announcement = { id:string; title:string; body:string; kind:string; created_at:string };
type Decision = { id:string; title:string; body:string; decision_no:string; created_at:string };
type AppData = { user:User; membership:null|{community_id:string;role:"owner"|"manager"|"resident"}; community?:Community; members?:Member[]; residents?:Resident[]; dues?:Due[]; expenses?:Expense[]; announcements?:Announcement[]; decisions?:Decision[] };
type Page = "dashboard"|"dues"|"expenses"|"announcements"|"decisions"|"residents"|"settings";
type Modal = null|"resident"|"due"|"expense"|"announcement"|"decision";

const money=(value:number)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0}).format(value||0);
const date=(value:string)=>new Intl.DateTimeFormat("tr-TR",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value));
const initials=(name:string)=>name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toLocaleUpperCase("tr");
const roleName={owner:"Yönetim sahibi",manager:"Yönetici",resident:"Sakin"};

export default function ApartmentApp({user}:{user:User}){
  const [data,setData]=useState<AppData|null>(null);
  const [loading,setLoading]=useState(true);
  const [page,setPage]=useState<Page>("dashboard");
  const [modal,setModal]=useState<Modal>(null);
  const [deleting,setDeleting]=useState<{type:string,id:string,name:string}|null>(null);
  const canManage=data?.membership?.role==="owner"||data?.membership?.role==="manager";

  async function load(){setLoading(true);try{const response=await fetch("/api/app",{cache:"no-store"});const json=await response.json();if(!response.ok)throw new Error(json.error);setData(json)}catch(error){toast.error(error instanceof Error?error.message:"Veriler yüklenemedi.")}finally{setLoading(false)}}
  async function action(payload:Record<string,unknown>,success?:string){const response=await fetch("/api/app",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const json=await response.json();if(!response.ok)throw new Error(json.error||"İşlem tamamlanamadı.");if(success)toast.success(success);await load()}
  async function logout(){await fetch("/api/auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"logout"})});window.location.reload()}
  useEffect(()=>{
    let active=true;
    fetch("/api/app",{cache:"no-store"})
      .then(async response=>{const json=await response.json();if(!response.ok)throw new Error(json.error);return json})
      .then(json=>{if(active)setData(json)})
      .catch(error=>toast.error(error instanceof Error?error.message:"Veriler yüklenemedi."))
      .finally(()=>{if(active)setLoading(false)});
    return ()=>{active=false};
  },[]);

  if(loading)return <LoadingScreen/>;
  if(!data?.membership)return <WelcomeSetup user={user} onAction={async p=>{await action(p);toast.success("Yönetim alanınız hazır.")}}/>;
  const community=data.community!;
  const dues=data.dues||[], expenses=data.expenses||[], announcements=data.announcements||[], decisions=data.decisions||[], residents=data.residents||[];
  const unpaid=dues.filter(x=>x.status!=="paid");
  const collected=dues.filter(x=>x.status==="paid").reduce((s,x)=>s+x.amount,0);
  const expenseTotal=expenses.reduce((s,x)=>s+x.amount,0);
  const nav:[Page,string,typeof Gauge][]=[['dashboard','Genel Bakış',Gauge],['dues','Aidat & Borçlar',CircleDollarSign],['expenses','Giderler',ReceiptText],['announcements','Duyurular',Megaphone],['decisions','Karar Defteri',BookOpenCheck],['residents','Sakinler',Users],['settings','Ayarlar',Settings]];

  return <SidebarProvider>
    <AppSidebar community={community} nav={nav} page={page} unpaidCount={unpaid.length} role={data.membership.role} onNavigate={setPage}/>
    <SidebarInset>
      <header className="app-header"><div className="header-left"><SidebarTrigger><Menu/></SidebarTrigger><div><small>{new Intl.DateTimeFormat('tr-TR',{dateStyle:'full'}).format(new Date())}</small><strong>{nav.find(n=>n[0]===page)?.[1]}</strong></div></div><div className="header-actions"><Button variant="outline" size="icon" onClick={()=>setPage("announcements")} aria-label="Bildirimler"><Bell/></Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" className="profile-trigger"><span>{initials(user.displayName)}</span><div><strong>{user.displayName}</strong><small>{roleName[data.membership.role]}</small></div></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-60"><DropdownMenuLabel>{user.email}</DropdownMenuLabel><DropdownMenuSeparator/><DropdownMenuItem onClick={()=>setPage('settings')}><Settings/>Ayarlar</DropdownMenuItem><DropdownMenuItem onClick={logout}><LogOut/>Çıkış yap</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header>
      <main className="app-main">
        {page==='dashboard'&&<Dashboard community={community} collected={collected} unpaid={unpaid} expenses={expenses} expenseTotal={expenseTotal} announcements={announcements} dues={dues} canManage={!!canManage} onAdd={setModal} onPage={setPage}/>} 
        {page==='dues'&&<DuesPage dues={dues} canManage={!!canManage} onAdd={()=>setModal('due')} onToggle={id=>action({action:'toggleDue',id},'Ödeme durumu güncellendi.')} onDelete={(id,name)=>setDeleting({type:'dues',id,name})}/>} 
        {page==='expenses'&&<CardPage title="Giderler" description="Ortak alan harcamalarını şeffaf biçimde izleyin." items={expenses} kind="expense" canManage={!!canManage} onAdd={()=>setModal('expense')} onDelete={(id,name)=>setDeleting({type:'expenses',id,name})}/>} 
        {page==='announcements'&&<CardPage title="Duyurular" description="Sakinlerin haberdar olması gereken gelişmeleri paylaşın." items={announcements} kind="announcement" canManage={!!canManage} onAdd={()=>setModal('announcement')} onDelete={(id,name)=>setDeleting({type:'announcements',id,name})}/>} 
        {page==='decisions'&&<CardPage title="Karar Defteri" description="Yönetim kararlarını tarih ve numarasıyla kaydedin." items={decisions} kind="decision" canManage={!!canManage} onAdd={()=>setModal('decision')} onDelete={(id,name)=>setDeleting({type:'decisions',id,name})}/>} 
        {page==='residents'&&<ResidentsPage residents={residents} canManage={!!canManage} onAdd={()=>setModal('resident')} onDelete={(id,name)=>setDeleting({type:'residents',id,name})}/>} 
        {page==='settings'&&<SettingsPage data={data} onAction={action}/>} 
      </main>
    </SidebarInset>
    <RecordDialog type={modal} community={community} onClose={()=>setModal(null)} onSubmit={async payload=>{await action(payload,'Kayıt eklendi.');setModal(null)}}/>
    <AlertDialog open={!!deleting} onOpenChange={open=>!open&&setDeleting(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Kayıt silinsin mi?</AlertDialogTitle><AlertDialogDescription>“{deleting?.name}” kalıcı olarak silinecek. Bu işlem geri alınamaz.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Vazgeç</AlertDialogCancel><AlertDialogAction className="bg-destructive text-white" onClick={async()=>{if(!deleting)return;await action({action:'delete',type:deleting.type,id:deleting.id},'Kayıt silindi.');setDeleting(null)}}>Sil</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Toaster richColors position="bottom-right"/>
  </SidebarProvider>
}

function AppSidebar({community,nav,page,unpaidCount,role,onNavigate}:{community:Community;nav:[Page,string,typeof Gauge][];page:Page;unpaidCount:number;role:Member["role"];onNavigate:(page:Page)=>void}){
  const {setOpenMobile}=useSidebar();
  function go(next:Page){onNavigate(next);setOpenMobile(false)}
  return <Sidebar className="apartman-sidebar" collapsible="icon">
    <SidebarHeader className="p-5"><button className="brand-button" onClick={()=>go("dashboard")}><span className="brand-icon">A</span><span className="brand-copy">apartman<b>OS</b></span></button><button className="community-switch" onClick={()=>go("settings")}><span>{community.name[0]?.toLocaleUpperCase('tr')}</span><div><strong>{community.name}</strong><small>{community.block_count} blok · {community.unit_count} daire</small></div></button></SidebarHeader>
    <SidebarContent className="px-3"><SidebarMenu>{nav.map(([key,label,Icon])=><SidebarMenuItem key={key}><SidebarMenuButton isActive={page===key} onClick={()=>go(key)} tooltip={label}><Icon/><span>{label}</span>{key==='dues'&&unpaidCount>0?<SidebarMenuBadge>{unpaidCount}</SidebarMenuBadge>:null}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent>
    <SidebarFooter className="p-4"><div className="role-card"><ShieldCheck/><div><strong>{roleName[role]}</strong><small>Yetkiniz sunucuda korunur</small></div></div></SidebarFooter>
  </Sidebar>
}

function LoadingScreen(){return <main className="loading-screen"><div className="loading-mark">A</div><p>apartmanOS hazırlanıyor…</p></main>}

function WelcomeSetup({user,onAction}:{user:User;onAction:(p:Record<string,unknown>)=>Promise<void>}){
  const [tab,setTab]=useState<'create'|'join'>('create');const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=Object.fromEntries(new FormData(e.currentTarget));try{await onAction({action:tab==='create'?'createCommunity':'joinCommunity',...form})}catch(error){toast.error(error instanceof Error?error.message:'İşlem tamamlanamadı.')}finally{setBusy(false)}}
  return <main className="setup-page"><section className="setup-card"><div className="setup-brand"><span>A</span><div><b>apartmanOS</b><small>Hoş geldiniz, {user.displayName}</small></div></div><h1>Yönetim alanınızı seçin</h1><p>Kendi apartmanınızı oluşturun veya yöneticinizin verdiği davet koduyla katılın.</p><div className="setup-tabs"><button className={tab==='create'?'active':''} onClick={()=>setTab('create')}>Yeni apartman oluştur</button><button className={tab==='join'?'active':''} onClick={()=>setTab('join')}>Davetle katıl</button></div><form onSubmit={submit}>{tab==='create'?<><Field label="Site / apartman adı" name="name" placeholder="Örn. Güneş Apartmanı"/><div className="form-grid"><Field label="Blok sayısı" name="blockCount" type="number" defaultValue="1"/><Field label="Daire sayısı" name="unitCount" type="number" defaultValue="12"/></div><div className="form-grid"><Field label="Aylık aidat" name="monthlyDue" type="number" defaultValue="1000"/><Field label="Yönetim dönemi" name="period" defaultValue={String(new Date().getFullYear())}/></div></>:<><Field label="Davet kodu" name="code" placeholder="Örn. A7K9P2M"/><Field label="Daireniz" name="unit" placeholder="Örn. A Blok · Daire 4"/></>}<Button className="w-full" disabled={busy}>{busy?'Kaydediliyor…':tab==='create'?'Yönetim alanını oluştur':'Apartmana katıl'}</Button></form></section><Toaster richColors/></main>
}

function Field({label,name,...props}:{label:string;name:string}&ComponentProps<typeof Input>){return <div className="field-wrap"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} required {...props}/></div>}

function Dashboard({community,collected,unpaid,expenses,expenseTotal,announcements,dues,canManage,onAdd,onPage}:{community:Community;collected:number;unpaid:Due[];expenses:Expense[];expenseTotal:number;announcements:Announcement[];dues:Due[];canManage:boolean;onAdd:(m:Modal)=>void;onPage:(p:Page)=>void}){
  const paid=dues.length-unpaid.length;const rate=dues.length?Math.round(paid/dues.length*100):0;
  return <><div className="page-heading"><div><h1>{community.name}</h1><p>Bugün bilmeniz gerekenler tek ekranda.</p></div>{canManage?<div className="heading-actions"><Button variant="outline" onClick={()=>onAdd('announcement')}><Megaphone/>Duyuru yap</Button><Button onClick={()=>onAdd('expense')}><Plus/>Gider ekle</Button></div>:null}</div><section className="metric-grid"><Metric label="Toplanan aidat" value={money(collected)} note={`${paid} ödeme tamamlandı`} tone="teal"/><Metric label="Toplam borç" value={money(unpaid.reduce((s,x)=>s+x.amount,0))} note={`${unpaid.length} bekleyen ödeme`} tone="red"/><Metric label="Toplam gider" value={money(expenseTotal)} note={`${expenses.length} gider kaydı`} tone="amber"/><Metric label="Güncel kasa" value={money(collected-expenseTotal)} note="Tahmini bakiye" tone="blue"/></section><section className="dashboard-grid"><div className="panel"><PanelHead title="Aidat durumu" action="Detaylar" onClick={()=>onPage('dues')}/><div className="progress-wrap"><div className="progress-ring" style={{background:`conic-gradient(#16a99c ${rate*3.6}deg,#eaf0f4 0)`}}><span>%{rate}<small>Tahsilat</small></span></div><div className="summary-list"><p><span>Ödeyen daire</span><b>{paid} / {dues.length}</b></p><p><span>Toplanan</span><b>{money(collected)}</b></p><p><span>Beklenen</span><b>{money(unpaid.reduce((s,x)=>s+x.amount,0))}</b></p></div></div></div><div className="panel"><PanelHead title="Son duyurular" action="Tümünü gör" onClick={()=>onPage('announcements')}/>{announcements.length?<div className="mini-list">{announcements.slice(0,3).map(a=><div key={a.id}><span>{a.kind}</span><div><b>{a.title}</b><small>{a.body}</small></div></div>)}</div>:<Empty text="Henüz duyuru yok."/>}</div><div className="panel full"><PanelHead title="Son giderler" action="Tümünü gör" onClick={()=>onPage('expenses')}/>{expenses.length?<div className="summary-list">{expenses.slice(0,5).map(x=><p key={x.id}><span>{x.title} · {date(x.expense_date)}</span><b>{money(x.amount)}</b></p>)}</div>:<Empty text="Henüz gider kaydı yok."/>}</div></section></>
}

function Metric({label,value,note,tone}:{label:string;value:string;note:string;tone:string}){return <article className={`metric ${tone}`}><small>{label}</small><strong>{value}</strong><span>{note}</span></article>}
function PanelHead({title,action,onClick}:{title:string;action:string;onClick:()=>void}){return <div className="panel-head"><h2>{title}</h2><button onClick={onClick}>{action} →</button></div>}
function Empty({text}:{text:string}){return <div className="empty"><span>⌁</span><p>{text}</p></div>}

function PageHeading({title,description,button,onClick}:{title:string;description:string;button?:string;onClick?:()=>void}){return <div className="page-heading"><div><h1>{title}</h1><p>{description}</p></div>{button&&onClick?<Button onClick={onClick}><Plus/>{button}</Button>:null}</div>}

function DuesPage({dues,canManage,onAdd,onToggle,onDelete}:{dues:Due[];canManage:boolean;onAdd:()=>void;onToggle:(id:string)=>void;onDelete:(id:string,name:string)=>void}){const [q,setQ]=useState('');const rows=dues.filter(x=>(x.resident_name+x.unit).toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr')));return <><PageHeading title="Aidat & Borçlar" description="Tahsilatları ve geciken ödemeleri takip edin." button={canManage?'Aidat kaydı ekle':undefined} onClick={onAdd}/><div className="table-panel"><div className="table-tools"><Input placeholder="Sakin veya daire ara" value={q} onChange={e=>setQ(e.target.value)}/><Badge variant="secondary">Güncel dönem</Badge></div><Table><TableHeader><TableRow><TableHead>Sakin</TableHead><TableHead>Tutar</TableHead><TableHead>Son ödeme</TableHead><TableHead>Durum</TableHead>{canManage?<TableHead/>:null}</TableRow></TableHeader><TableBody>{rows.map(x=><TableRow key={x.id}><TableCell><b>{x.resident_name}</b><small className="cell-sub">{x.unit}</small></TableCell><TableCell>{money(x.amount)}</TableCell><TableCell>{date(x.due_date)}</TableCell><TableCell><Status value={x.status}/></TableCell>{canManage?<TableCell className="actions"><Button size="sm" variant="outline" onClick={()=>onToggle(x.id)}>{x.status==='paid'?'Bekliyor yap':'Ödendi yap'}</Button><Button size="icon-sm" variant="ghost" onClick={()=>onDelete(x.id,x.resident_name)}><Trash2/></Button></TableCell>:null}</TableRow>)}</TableBody></Table>{!rows.length?<Empty text="Gösterilecek aidat kaydı yok."/>:null}</div></>}
function Status({value}:{value:string}){return <Badge className={value==='paid'?'status-paid':value==='late'?'status-late':'status-pending'}>{value==='paid'?'Ödendi':value==='late'?'Gecikmiş':'Bekliyor'}</Badge>}

type CardItem=Expense|Announcement|Decision;
function CardPage({title,description,items,kind,canManage,onAdd,onDelete}:{title:string;description:string;items:CardItem[];kind:'expense'|'announcement'|'decision';canManage:boolean;onAdd:()=>void;onDelete:(id:string,name:string)=>void}){return <><PageHeading title={title} description={description} button={canManage?(kind==='expense'?'Gider ekle':kind==='announcement'?'Duyuru yap':'Karar ekle'):undefined} onClick={onAdd}/>{items.length?<section className="card-grid">{items.map(item=>{const expense=kind==='expense'?item as Expense:null;const announcement=kind==='announcement'?item as Announcement:null;const decision=kind==='decision'?item as Decision:null;return <article className="record-card" key={item.id}><div className="record-meta"><Badge variant="secondary">{expense?.category||announcement?.kind||decision?.decision_no}</Badge><span>{date(item.created_at)}</span></div><h2>{item.title}</h2><p>{expense?.note||announcement?.body||decision?.body||'Açıklama girilmedi.'}</p><footer>{expense?<b>{money(expense.amount)}</b>:<span>Yönetim kaydı</span>}{canManage?<Button size="icon-sm" variant="ghost" onClick={()=>onDelete(item.id,item.title)}><Trash2/></Button>:null}</footer></article>})}</section>:<div className="table-panel"><Empty text={`Henüz ${title.toLocaleLowerCase('tr')} kaydı yok.`}/></div>}</>}

function ResidentsPage({residents,canManage,onAdd,onDelete}:{residents:Resident[];canManage:boolean;onAdd:()=>void;onDelete:(id:string,name:string)=>void}){const [q,setQ]=useState('');const rows=residents.filter(x=>(x.name+x.unit).toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr')));return <><PageHeading title="Sakinler" description="Daire ve iletişim bilgilerini yönetin." button={canManage?'Sakin ekle':undefined} onClick={onAdd}/><div className="table-panel"><div className="table-tools"><Input placeholder="Sakin veya daire ara" value={q} onChange={e=>setQ(e.target.value)}/></div><Table><TableHeader><TableRow><TableHead>Sakin</TableHead><TableHead>Daire</TableHead><TableHead>Telefon</TableHead><TableHead>Oturum</TableHead>{canManage?<TableHead/>:null}</TableRow></TableHeader><TableBody>{rows.map(x=><TableRow key={x.id}><TableCell><b>{x.name}</b></TableCell><TableCell>{x.unit}</TableCell><TableCell>{x.phone||'—'}</TableCell><TableCell>{x.occupancy}</TableCell>{canManage?<TableCell className="actions"><Button size="icon-sm" variant="ghost" onClick={()=>onDelete(x.id,x.name)}><Trash2/></Button></TableCell>:null}</TableRow>)}</TableBody></Table>{!rows.length?<Empty text="Henüz sakin kaydı yok."/>:null}</div></>}

function SettingsPage({data,onAction}:{data:AppData;onAction:(p:Record<string,unknown>,s?:string)=>Promise<void>}){const c=data.community!, role=data.membership!.role;const [busy,setBusy]=useState(false);async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{await onAction({action:'updateCommunity',...Object.fromEntries(new FormData(e.currentTarget))},'Apartman bilgileri güncellendi.')}catch(error){toast.error(error instanceof Error?error.message:'Kaydedilemedi.')}finally{setBusy(false)}}return <><PageHeading title="Ayarlar" description="Apartman bilgilerini, davet kodunu ve ekip yetkilerini yönetin."/><section className="settings-grid"><form className="panel settings-form" onSubmit={save}><h2>Site bilgileri</h2><Field label="Site / apartman adı" name="name" defaultValue={c.name} disabled={role==='resident'}/><div className="form-grid"><Field label="Blok sayısı" name="blockCount" type="number" defaultValue={String(c.block_count)} disabled={role==='resident'}/><Field label="Daire sayısı" name="unitCount" type="number" defaultValue={String(c.unit_count)} disabled={role==='resident'}/></div><div className="form-grid"><Field label="Aylık aidat" name="monthlyDue" type="number" defaultValue={String(c.monthly_due)} disabled={role==='resident'}/><Field label="Yönetim dönemi" name="period" defaultValue={c.period} disabled={role==='resident'}/></div>{role!=='resident'?<Button disabled={busy}>{busy?'Kaydediliyor…':'Değişiklikleri kaydet'}</Button>:null}</form>{role!=='resident'?<div className="panel invite-panel"><h2>Davet kodu</h2><p>Sakinler bu kodla yalnızca bu apartmana katılır.</p><div className="invite-code"><b>{c.invite_code}</b><Button variant="outline" onClick={()=>navigator.clipboard.writeText(c.invite_code).then(()=>toast.success('Davet kodu kopyalandı.'))}>Kopyala</Button></div>{role==='owner'?<Button variant="ghost" onClick={()=>onAction({action:'regenerateInvite'},'Yeni davet kodu oluşturuldu.')}>Yeni kod oluştur</Button>:null}</div>:null}<div className="panel members-panel"><h2>Üyeler ve roller</h2><div className="member-list">{(data.members||[]).map(m=><div key={m.id}><span className="member-avatar">{initials(m.display_name)}</span><div><b>{m.display_name}</b><small>{m.unit||(role==='owner'?m.email:'Apartman üyesi')}</small></div>{role==='owner'&&m.role!=='owner'?<Select value={m.role} onValueChange={value=>onAction({action:'updateMemberRole',id:m.id,role:value},'Üye rolü güncellendi.')}><SelectTrigger className="w-32"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="resident">Sakin</SelectItem><SelectItem value="manager">Yönetici</SelectItem></SelectContent></Select>:<Badge variant="secondary">{roleName[m.role]}</Badge>}</div>)}</div></div></section></>}

function RecordDialog({type,community,onClose,onSubmit}:{type:Modal;community:Community;onClose:()=>void;onSubmit:(p:Record<string,unknown>)=>Promise<void>}){const [busy,setBusy]=useState(false);const title=type==='resident'?'Sakin ekle':type==='due'?'Aidat kaydı ekle':type==='expense'?'Gider ekle':type==='announcement'?'Duyuru yap':'Karar ekle';async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=Object.fromEntries(new FormData(e.currentTarget));const actions={resident:'addResident',due:'addDue',expense:'addExpense',announcement:'addAnnouncement',decision:'addDecision'};try{await onSubmit({action:actions[type!],...f})}catch(error){toast.error(error instanceof Error?error.message:'Kaydedilemedi.')}finally{setBusy(false)}}return <Dialog open={!!type} onOpenChange={open=>!open&&onClose()}><DialogContent><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>Bilgileri eksiksiz doldurun. Kayıt apartmanınıza özel saklanır.</DialogDescription></DialogHeader><form onSubmit={submit} className="dialog-form">{type==='resident'?<><Field label="Ad soyad" name="name"/><Field label="Daire" name="unit" placeholder="A Blok · Daire 1"/><Field label="Telefon" name="phone" required={false}/><SelectField label="Oturum türü" name="occupancy" options={['Ev sahibi','Kiracı']}/></>:type==='due'?<><Field label="Sakin adı" name="residentName"/><Field label="Daire" name="unit"/><Field label="Tutar" name="amount" type="number" min="1" defaultValue={String(community.monthly_due)}/><Field label="Son ödeme tarihi" name="dueDate" type="date"/></>:type==='expense'?<><Field label="Gider açıklaması" name="title"/><SelectField label="Kategori" name="category" options={['Bakım','Fatura','Temizlik','Peyzaj','Diğer']}/><Field label="Tutar" name="amount" type="number" min="1"/><Field label="Gider tarihi" name="expenseDate" type="date"/><TextField label="Not" name="note" required={false}/></>:type==='announcement'?<><Field label="Başlık" name="title"/><TextField label="Açıklama" name="body"/><SelectField label="Tür" name="kind" options={['Bilgilendirme','Önemli','Toplantı']}/></>:type==='decision'?<><Field label="Karar başlığı" name="title"/><TextField label="Karar metni" name="body"/><Field label="Karar numarası" name="decisionNo" defaultValue={`${new Date().getFullYear()} / 1`}/></>:null}<DialogFooter><Button type="button" variant="outline" onClick={onClose}>Vazgeç</Button><Button disabled={busy}>{busy?'Kaydediliyor…':'Kaydet'}</Button></DialogFooter></form></DialogContent></Dialog>}

function TextField({label,name,required=true}:{label:string;name:string;required?:boolean}){return <div className="field-wrap"><Label htmlFor={name}>{label}</Label><Textarea id={name} name={name} required={required}/></div>}
function SelectField({label,name,options}:{label:string;name:string;options:string[]}){const [value,setValue]=useState(options[0]);return <div className="field-wrap"><Label>{label}</Label><input type="hidden" name={name} value={value}/><Select value={value} onValueChange={setValue}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select></div>}
