"use client";

import { FormEvent, useState } from "react";
import { ArrowLeft, LockKeyhole, Mail } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import LogoMark from "./logo-mark";

export default function PasswordRecovery({token}:{token:string}){const [busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const values=Object.fromEntries(new FormData(event.currentTarget));try{const response=await fetch("/api/auth/recovery",{method:token?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(token?{token,password:values.password}:{email:values.email})});const result=await response.json() as {error?:string;message?:string};if(!response.ok)throw new Error(result.error||"İşlem tamamlanamadı.");setMessage(result.message||"İşlem tamamlandı.")}catch(reason){setError(reason instanceof Error?reason.message:"İşlem tamamlanamadı.")}finally{setBusy(false)}}return <main className="signin-page"><section className="signin-card auth-card"><div className="setup-brand"><LogoMark className="setup-logo"/><div><b>apartmanOS</b><small>Güvenli hesap işlemleri</small></div></div><h1>{token?"Yeni şifrenizi belirleyin":"Şifrenizi mi unuttunuz?"}</h1><p>{token?"Hesabınız için yeni ve güçlü bir şifre oluşturun.":"E-posta adresinizi yazın, size güvenli bir yenileme bağlantısı gönderelim."}</p><form className="auth-form" onSubmit={submit}>{token?<div className="field-wrap auth-field"><Label htmlFor="password">Yeni şifre</Label><div><LockKeyhole/><Input id="password" name="password" type="password" minLength={8} maxLength={128} required placeholder="En az 8 karakter"/></div></div>:<div className="field-wrap auth-field"><Label htmlFor="email">E-posta adresi</Label><div><Mail/><Input id="email" name="email" type="email" autoComplete="email" required placeholder="ornek@email.com"/></div></div>}{error?<p className="auth-error">{error}</p>:null}{message?<p className="auth-success">{message}</p>:null}<Button disabled={busy}>{busy?"Lütfen bekleyin…":token?"Şifreyi yenile":"Yenileme bağlantısı gönder"}</Button></form><a className="back-login" href="/giris"><ArrowLeft/>Giriş sayfasına dön</a></section></main>}
