import { env } from "cloudflare:workers";
import { NextResponse } from "next/server";
import { getSessionUser, sameOrigin } from "@/app/auth";
import { getDatabase } from "@/db";
import { ensurePropertySchema, unitLabel } from "@/app/api/app/properties";

const allowed=new Set(["application/pdf","image/jpeg","image/png","image/webp","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]),fail=(message:string,status=400)=>NextResponse.json({error:message},{status}),id=()=>crypto.randomUUID();
async function membership(userId:string,communityId:string){return getDatabase().prepare("SELECT role,unit FROM members WHERE user_id=? AND community_id=?").bind(userId,communityId).first<{role:string;unit:string|null}>()}

export async function POST(request:Request){
  if(!sameOrigin(request))return fail("Geçersiz istek.",403);const user=await getSessionUser();if(!user)return fail("Oturum açmanız gerekiyor.",401);await ensurePropertySchema();const form=await request.formData(),communityId=String(form.get("communityId")||""),unitId=String(form.get("unitId")||""),file=form.get("file"),member=await membership(user.userId,communityId);if(!member||!["owner","manager"].includes(member.role))return fail("Daire belgesi yüklemek için yönetici yetkisi gerekiyor.",403);const unit=await getDatabase().prepare("SELECT id FROM property_units WHERE id=? AND community_id=?").bind(unitId,communityId).first();if(!unit)return fail("Daire bulunamadı.",404);if(!(file instanceof File)||!file.size)return fail("Yüklenecek belgeyi seçin.");if(!allowed.has(file.type))return fail("PDF, Word, Excel, JPG, PNG veya WebP dosyası kullanın.",415);if(file.size>15*1024*1024)return fail("Belge en fazla 15 MB olabilir.",413);
  const bucket=env.BUCKET as R2Bucket|undefined;if(!bucket)return fail("Dosya depolama alanı kullanılamıyor.",503);const documentId=id(),safeName=file.name.replace(/[^a-zA-Z0-9._-]+/g,"-").slice(-100)||"belge",objectKey=`units/${communityId}/${unitId}/${documentId}-${safeName}`,createdAt=new Date().toISOString();await bucket.put(objectKey,file.stream(),{httpMetadata:{contentType:file.type}});try{await getDatabase().prepare("INSERT INTO unit_documents (id,community_id,unit_id,object_key,file_name,content_type,size,uploaded_by,created_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(documentId,communityId,unitId,objectKey,file.name.slice(0,200),file.type,file.size,user.userId,createdAt).run()}catch(error){await bucket.delete(objectKey);throw error}return NextResponse.json({ok:true,documentId});
}

export async function GET(request:Request){
  const user=await getSessionUser();if(!user)return fail("Oturum açmanız gerekiyor.",401);await ensurePropertySchema();const documentId=new URL(request.url).searchParams.get("id")||"",row=await getDatabase().prepare("SELECT d.*,u.unit_no,b.name AS block_name FROM unit_documents d JOIN property_units u ON u.id=d.unit_id JOIN property_blocks b ON b.id=u.block_id WHERE d.id=?").bind(documentId).first<{id:string;community_id:string;object_key:string;file_name:string;content_type:string;size:number;unit_no:string;block_name:string}>();if(!row)return fail("Belge bulunamadı.",404);const member=await membership(user.userId,row.community_id);if(!member)return fail("Bu belgeye erişiminiz yok.",403);const own=[unitLabel(row.block_name,row.unit_no),row.unit_no].some(value=>value.toLocaleLowerCase('tr')===String(member.unit||'').toLocaleLowerCase('tr'));if(!["owner","manager","staff"].includes(member.role)&&!own)return fail("Bu belgeye erişiminiz yok.",403);const bucket=env.BUCKET as R2Bucket|undefined;if(!bucket)return fail("Dosya depolama alanı kullanılamıyor.",503);const object=await bucket.get(row.object_key);if(!object)return fail("Belge bulunamadı.",404);return new Response(object.body,{headers:{"content-type":row.content_type,"content-length":String(row.size),"content-disposition":`inline; filename*=UTF-8''${encodeURIComponent(row.file_name)}`,"cache-control":"private, max-age=300","x-content-type-options":"nosniff"}});
}
