import type { Metadata } from "next";
import SeoPage from "../seo-page";

const url="https://apartmanos.com.tr/hakkimizda";
export const metadata:Metadata={title:"Hakkımızda | Berkant Kul ve Stark Bilişim Hizmetleri",description:"apartmanOS’un amacı, geliştiricisi Berkant Kul ve Stark Bilişim Hizmetleri ile ilişkisi hakkında bilgi edinin.",alternates:{canonical:url}};
const structuredData={"@context":"https://schema.org","@graph":[{"@type":"AboutPage","@id":`${url}#webpage`,url,name:"apartmanOS Hakkında",isPartOf:{"@id":"https://apartmanos.com.tr/#website"},about:[{"@id":"https://apartmanos.com.tr/#software"},{"@id":"https://apartmanos.com.tr/#organization"},{"@id":"https://apartmanos.com.tr/#berkant-kul"}],inLanguage:"tr-TR"},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"apartmanOS",item:"https://apartmanos.com.tr/"},{"@type":"ListItem",position:2,name:"Hakkımızda",item:url}]}]};

export default function Page(){return <SeoPage eyebrow="apartmanOS hakkında" title="Apartman yönetimini herkes için daha anlaşılır hale getiriyoruz." lead="apartmanOS, apartman ve site yönetimindeki aidat, gider, duyuru, karar ve sakin iletişimi süreçlerini sade bir web uygulamasında birleştirmek amacıyla geliştirilmektedir." structuredData={structuredData}>
  <section><h2>apartmanOS nedir?</h2><p>apartmanOS; apartman yöneticileri ve sakinleri için geliştirilen web tabanlı bir yönetim uygulamasıdır. Ürün, günlük yönetim işlerini karmaşıklaştırmadan kayıt altına almayı ve her apartmanın kendi üyeleriyle bağımsız bir çalışma alanına sahip olmasını hedefler.</p><p>Uygulamanın ilk sürümünde aidat ve borç takibi, gider kayıtları, duyurular, karar defteri, sakin davetleri, kullanıcı rolleri, çoklu apartman üyeliği ve rapor dışa aktarma özellikleri yer almaktadır.</p></section>
  <section><h2>Kim geliştiriyor?</h2><p>apartmanOS, yazılım geliştirici <strong>Berkant Kul</strong> tarafından geliştirilmekte ve <strong>Stark Bilişim Hizmetleri</strong> çatısı altında sunulmaktadır. Ürünün tasarım, kullanıcı deneyimi ve teknik geliştirme süreçleri gerçek apartman yönetimi ihtiyaçları dikkate alınarak devam etmektedir.</p><p><a className="text-link" href="https://berkantkul.com.tr" target="_blank" rel="noreferrer">Berkant Kul’un kişisel web sitesini ziyaret edin</a></p></section>
  <section><h2>Ürün yaklaşımımız</h2><div className="seo-card-grid"><article><h3>Sadelik</h3><p>Teknik deneyimi farklı olan kullanıcıların temel işlemleri yardıma ihtiyaç duymadan tamamlayabilmesini amaçlıyoruz.</p></article><article><h3>Şeffaflık</h3><p>Aidat, ödeme, gider ve karar kayıtlarının ilgili kişilerce düzenli ve anlaşılır biçimde izlenmesini önemsiyoruz.</p></article><article><h3>Ayrılmış yönetim alanları</h3><p>Her apartman veya site kendi üyeleri, yetkileri ve kayıtlarıyla bağımsız bir topluluk olarak çalışır.</p></article><article><h3>Sürekli gelişim</h3><p>Kullanıcı geri bildirimleri doğrultusunda bildirim, raporlama ve yönetim akışlarını geliştirmeye devam ediyoruz.</p></article></div></section>
  <aside className="seo-related"><strong>apartmanOS’u keşfedin</strong><a href="/apartman-yonetim-programi">Apartman yönetim programı rehberi</a><a href="/aidat-takip-programi">Aidat takip programı rehberi</a></aside>
 </SeoPage>}
