import type { Metadata } from "next";
import SeoPage from "../seo-page";

const url="https://apartmanos.com.tr/aidat-takip-programi";
export const metadata:Metadata={title:"Apartman Aidat Takip Programı | Borç ve Ödeme Takibi",description:"Daire bazında apartman aidatı oluşturun; ödeme, borç ve tahsilat durumunu takip edin. Gider ve raporlarla birlikte çalışan kolay aidat takip programı.",alternates:{canonical:url},openGraph:{type:"article",locale:"tr_TR",url,title:"Apartman Aidat Takip Programı | apartmanOS",description:"Apartman aidatlarını, borçları ve ödemeleri daire bazında düzenli biçimde takip edin."}};
const faqs=[{q:"Aidatlar her daire için tek tek mi oluşturulur?",a:"Yönetici aylık aidatları bütün sakinler için tek işlemle oluşturabilir; gerektiğinde kayıtları daire bazında takip eder."},{q:"Ödenen ve bekleyen aidatlar görülebilir mi?",a:"Evet. Toplanan aidat, bekleyen ödeme ve dairelerin ödeme durumu yönetim panelinde ayrı olarak gösterilir."},{q:"Aidat kayıtları dışa aktarılabilir mi?",a:"Aidat ve gider kayıtları Excel uyumlu dosya olarak indirilebilir; yazdırma görünümü üzerinden PDF olarak kaydedilebilir."}];
const structuredData={"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":`${url}#webpage`,url,name:"Apartman Aidat Takip Programı",description:"Daire bazında aidat, borç ve ödeme takibi için web tabanlı uygulama.",isPartOf:{"@id":"https://apartmanos.com.tr/#website"},about:{"@id":"https://apartmanos.com.tr/#software"},inLanguage:"tr-TR"},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"apartmanOS",item:"https://apartmanos.com.tr/"},{"@type":"ListItem",position:2,name:"Aidat Takip Programı",item:url}]},{"@type":"FAQPage",mainEntity:faqs.map(x=>({"@type":"Question",name:x.q,acceptedAnswer:{"@type":"Answer",text:x.a}}))}]};

export default function Page(){return <SeoPage eyebrow="Aidat takip programı" title="Apartman aidatlarını ve borçları daire bazında takip edin." lead="apartmanOS aidat takip sistemi; aylık aidatların oluşturulması, ödemelerin kaydedilmesi ve bekleyen borçların görülmesi için yöneticilere sade bir çalışma alanı sunar." structuredData={structuredData}>
  <section><h2>Aidat takibinde düzen neden önemlidir?</h2><p>Apartman aidatları yalnızca aylık tutarı belirlemekten ibaret değildir. Hangi dairenin ne kadar borcu olduğu, hangi ödemenin tamamlandığı ve ortak giderlerin nasıl karşılandığı düzenli biçimde izlenmelidir. Dağınık mesajlar veya kişisel notlar, dönem sonunda kontrolü zorlaştırır.</p><p>apartmanOS, aidat ve gider hareketlerini ilgili apartmanın kendi yönetim alanında tutar. Böylece yönetici güncel durumu tek ekrandan değerlendirirken sakinler de yetkileri kapsamında kendi apartmanlarının kayıtlarına erişebilir.</p></section>
  <section><h2>apartmanOS ile aidat süreci</h2><div className="seo-card-grid"><article><h3>Toplu aidat oluşturma</h3><p>Aylık aidatları bütün sakinler için tek tuşla oluşturun ve tekrar eden veri girişini azaltın.</p></article><article><h3>Daire bazlı durum</h3><p>Her dairenin aidat tutarını, son ödeme tarihini ve ödeme durumunu ayrı kayıtlarla görüntüleyin.</p></article><article><h3>Ödeme kaydı</h3><p>Tamamlanan tahsilatları işaretleyerek toplam ödeme ve bekleyen borç tutarlarını güncel tutun.</p></article><article><h3>Raporlama</h3><p>Aidat ve gider kayıtlarını Excel uyumlu dosyaya aktarın veya yazdırma ekranından PDF hazırlayın.</p></article></div></section>
  <section><h2>Aidat ile gider kayıtlarını birlikte değerlendirin</h2><p>Sağlıklı bir yönetim için yalnızca tahsilatı değil, toplanan tutarın hangi giderlerde kullanıldığını da izlemek gerekir. apartmanOS’taki gider bölümü; bakım, temizlik ve ortak alan harcamalarının ayrı kayıtlarla tutulmasını sağlar. Genel bakış ekranı da tahsilat ve borç durumunu yöneticinin hızlıca değerlendirebileceği bir özet halinde sunar.</p></section>
  <section><h2>Kimler kullanabilir?</h2><p>Tek bloklu apartman yöneticileri, çok bloklu site yönetimleri ve birden fazla topluluğu yöneten kullanıcılar aynı hesapla farklı yönetim alanlarına katılabilir. Her apartmanın üyeleri, aidatları ve giderleri kendi alanında ayrı tutulur.</p></section>
  <section><h2>Sıkça sorulan sorular</h2><div className="seo-faq">{faqs.map(x=><details key={x.q}><summary>{x.q}</summary><p>{x.a}</p></details>)}</div></section>
  <aside className="seo-related"><strong>İlgili içerik</strong><a href="/apartman-yonetim-programi">Apartman yönetim programı özellikleri</a><a href="/hakkimizda">apartmanOS hakkında</a></aside>
 </SeoPage>}
