import type { Metadata } from "next";
import SeoPage from "../seo-page";

const url="https://apartmanos.com.tr/apartman-yonetim-programi";
export const metadata:Metadata={title:"Apartman Yönetim Programı | Aidat, Gider ve Duyuru",description:"Apartman aidatı, borçlar, giderler, duyurular, karar defteri ve sakin kayıtlarını tek panelden yönetin. apartmanOS web tabanlı yönetim programını keşfedin.",alternates:{canonical:url},openGraph:{type:"article",locale:"tr_TR",url,title:"Apartman Yönetim Programı | apartmanOS",description:"Aidat, gider, duyuru ve sakin yönetimini tek panelde toplayan kolay apartman yönetim programı."}};
const faqs=[{q:"Apartman yönetim programı ne işe yarar?",a:"Aidat, borç, ödeme, gider, duyuru, karar ve sakin bilgilerini dağınık dosyalar yerine tek bir dijital yönetim alanında toplar."},{q:"apartmanOS telefondan kullanılabilir mi?",a:"Evet. Web tabanlı olduğu için güncel bir tarayıcı bulunan telefon, tablet ve bilgisayarlardan kullanılabilir."},{q:"Sakinler yönetime nasıl katılır?",a:"Yönetici katılma bağlantısını WhatsApp grubunda paylaşabilir veya e-posta daveti oluşturabilir. Sakin kendi hesabıyla ilgili apartmana katılır."},{q:"Bir kullanıcı birden fazla apartmanı yönetebilir mi?",a:"Evet. Kullanıcılar yetkili oldukları birden fazla apartman veya site arasında hesap değiştirmeden geçiş yapabilir."}];
const structuredData={"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":`${url}#webpage`,url,name:"Apartman Yönetim Programı",description:"Aidat, gider, duyuru, karar ve sakin kayıtları için web tabanlı apartman yönetim programı.",isPartOf:{"@id":"https://apartmanos.com.tr/#website"},about:{"@id":"https://apartmanos.com.tr/#software"},inLanguage:"tr-TR"},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"apartmanOS",item:"https://apartmanos.com.tr/"},{"@type":"ListItem",position:2,name:"Apartman Yönetim Programı",item:url}]},{"@type":"FAQPage",mainEntity:faqs.map(x=>({"@type":"Question",name:x.q,acceptedAnswer:{"@type":"Answer",text:x.a}}))}]};

export default function Page(){return <SeoPage eyebrow="Apartman yönetim programı" title="Apartman yönetiminde aidat, gider ve iletişimi tek yerde toplayın." lead="apartmanOS; yöneticilerin mali kayıtları düzenli tutmasını, sakinlerin kendi apartmanlarına güvenli biçimde katılmasını ve önemli bilgilerin kaybolmadan paylaşılmasını sağlayan web tabanlı bir apartman yönetim programıdır." structuredData={structuredData}>
  <section><h2>Apartman yönetim programı nedir?</h2><p>Apartman yönetim programı; dairelere ait aidat ve borçların, ortak giderlerin, yönetim kararlarının ve sakin iletişiminin dijital ortamda yürütülmesini sağlar. Defter, hesap tablosu ve mesaj grubu arasında bölünen bilgiler tek bir kayıt düzeninde bir araya gelir.</p><p>apartmanOS özellikle teknik bilgi gerektirmeyen, anlaşılır bir kullanım hedefler. Yönetici kendi apartmanını oluşturur; daire ve sakin kayıtlarını ekler, aylık aidatları toplu olarak tanımlar ve yönetim hareketlerini takip eder.</p></section>
  <section><h2>Bir apartman yöneticisinin temel ihtiyaçları</h2><div className="seo-card-grid"><article><h3>Aidat ve borç takibi</h3><p>Daire bazında tahakkuk, ödeme ve bekleyen borç durumunu görün. Aylık aidatları bütün sakinler için tek işlemle oluşturun.</p></article><article><h3>Gelir ve gider düzeni</h3><p>Ortak alan harcamalarını tarih, tutar ve kategori bilgisiyle kaydedin; dönemsel raporları Excel veya PDF olarak hazırlayın.</p></article><article><h3>Duyuru ve karar kayıtları</h3><p>Yönetim duyurularını sakinlerle paylaşın, alınan kararları tarihçesiyle birlikte dijital karar defterinde saklayın.</p></article><article><h3>Sakin ve yetki yönetimi</h3><p>Sakinleri bağlantı veya e-posta davetiyle apartmana alın; yönetici ve sakin rollerini ayrı biçimde yönetin.</p></article></div></section>
  <section><h2>Web tabanlı yönetimin avantajı</h2><p>Kurulum gerektirmeyen bir web uygulaması, yöneticinin yalnızca kendi bilgisayarına bağlı kalmasını önler. Yetkili kullanıcılar güncel verilere telefon, tablet veya bilgisayar üzerinden ulaşabilir. Bir kullanıcının birden fazla apartman veya siteye katılabilmesi, profesyonel yöneticiler için de kayıtların birbirine karışmadan yürütülmesini sağlar.</p></section>
  <section><h2>apartmanOS nasıl kullanılır?</h2><ol><li><strong>Hesap oluşturun:</strong> E-posta adresinizle veya Google hesabınızla giriş yapın.</li><li><strong>Apartmanınızı kurun:</strong> Apartman adı, blok ve daire sayısı ile yönetim dönemini tanımlayın.</li><li><strong>Sakinleri davet edin:</strong> Katılma bağlantısını paylaşın veya e-posta daveti oluşturun.</li><li><strong>Kayıtları yönetin:</strong> Aidat, ödeme, gider, duyuru ve karar işlemlerini ilgili bölümlerden yürütün.</li></ol></section>
  <section><h2>Sıkça sorulan sorular</h2><div className="seo-faq">{faqs.map(x=><details key={x.q}><summary>{x.q}</summary><p>{x.a}</p></details>)}</div></section>
  <aside className="seo-related"><strong>İlgili içerik</strong><a href="/aidat-takip-programi">Apartman aidat takip programı nasıl çalışır?</a><a href="/hakkimizda">apartmanOS’u kim geliştiriyor?</a></aside>
 </SeoPage>}
